---

# common
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: install git
    action: apt name=git state=installed update_cache=yes

# web
- hosts: web
  become: yes
  gather_facts: yes
  vars:
    app_version: origin/master
  serial: 1

  pre_tasks:
  - name: disable server in haproxy
    shell: echo "disable server mine/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: lb

  tasks:
  - name: install nginx
    action: apt name=nginx state=installed

  - name: write our nginx.conf
    action: template src=roles/web/templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: write our /etc/nginx/sites-available/default
    action: template src=roles/web/templates/default-site.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: clean existing website content
    file: path=/usr/share/nginx/html/ state=absent

  - name: deploy website content
    git: repo=https://github.com/alexvaua/site.git
         dest=/usr/share/nginx/html/
         version={{ app_version }}

  handlers:
  - name: restart nginx
    action: service name=nginx state=restarted

  post_tasks:
  - name: enable server in haproxy
    shell: echo "enable server mine/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: lb

# lb
- hosts: lb
  become: yes

  tasks:
  - name: Download and install haproxy and socat
    apt: pkg={{ item }} state=latest
    with_items:
    - haproxy
    - socat

  - name: Enable HAProxy
    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
    notify: restart haproxy

  - name: Configure the haproxy cnf file with hosts
    template: src=roles/lb/templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:
  - name: restart haproxy
    service: name=haproxy state=restarted

